disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - implicit_getter
  - line_length
  - force_cast
  - force_try
  - identifier_name
  - weak_delegate
opt_in_rules:
included: # paths to include during linting. `--path` is ignored if present.
  - rvcmac
  - rvcmacTests
  - rvcmacUITests
excluded:
